version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb  -dbPath /home/dynamodblocal/data/"
    # command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root #user must be root for some reason here.
  rabbitmq:
    image: rabbitmq:3.11.11-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

volumes:
  rabbitmq_data:
